### PR TITLE
Added download and extraction code

### LINKED ISSUE #2: Any utility in unzipper?
I've used this in the past to download the file to a temporary area, and unzip the contents to a temporary area.  Utility in a PR for this?

```r
download_unzip_series = function(series_instance_uid,
                                 verbose = TRUE) {
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  tfile = tempfile(fileext = ".zip")
  tfile = basename(tfile)
  if (verbose) {
    message("Downloading Series")
  }
  res =  TCIApathfinder::save_image_series(
    series_instance_uid = series_instance_uid, 
    out_dir = tdir, 
    out_file_name = tfile)
  if (verbose) {
    message("Unzipping Series")
  }  
  stopifnot(file.exists(res$out_file))
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  res = utils::unzip(zipfile = res$out_file  , exdir = tdir)
  L = list(files = res,
           dirs = unique(dirname(normalizePath(res))))
  return(L)
}
```

Also open to an `unzip_image_series` or `extract_image_series` that takes in either a `series_instance_uid` or a result from `save_image_series`
```r
extract_image_series = function(series_result) {
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  res = utils::unzip(zipfile = series_result$out_file, exdir = tdir)
  L = list(files = res,
           dirs = unique(dirname(normalizePath(res))))
  return(L)
}
```

### PR DESCRIPTION
**Pull request by muschellij2**
Fixes #2.  Added `save_extracted_image_series` and `extract_image_series` and have pass through for `out_dir`.

### CODE REVIEW

**Comment by muschellij2** [comment]
I've also added description and readme changes: https://travis-ci.com/muschellij2/TCIApathfinder/builds

**Comment by pamelarussell** [comment]
Thank you! Could you just make a few minor edits:

- Remove `.Rbuildignore`, `.gitignore`, `TCIApathfinder.Rproj` from repo
- I had erroneously labeled the version as `1.0.2` in `NEWS.md`; it should have been `1.0.3`. This will be `1.0.4`, so reflect that in `DESCRIPTION` and `NEWS.md`
- Could you add a couple of simple tests for `save_extracted_image_series`

**Comment by muschellij2** [comment]
`.Rbuildignore` should be there for ignoring files while building for CRAN such as `cran-comments.md`
`TCIApathfinder.Rproj` is for using RStudio to build the repo.  I can delete - but won't hurt build process.
`.gitignore` specifies which files you may have on your computer, but are not necessary for GitHub, such as `README_cache/`, when you had `cache = TRUE` for the readME.

Didn't have a test, but will add `save_extracted_image_series` as I put it in the `vignettes`

**Comment by pamelarussell** [comment]
Thanks for the test and updating `DESCRIPTION` and `NEWS`. I have my own local `.gitignore` and`.Rbuildignore` that list more artifacts of the development process on my end, so prefer to keep them out of the remote. If you think they should be in the repo, I can union yours with mine. Similar story with `Rproj`, just prefer to keep my own Rproj locally.

**Comment by muschellij2** [comment]
I tend to have them on GitHub as I like someone have the ability to open the project in RStudio.  Also, they are ignore files, so I don't mind them being a bit bloated.  If you feel strongly otherwise, though, I will drop them.

**Comment by pamelarussell** [comment]
I don't feel strongly, so let's keep them in the remote. Merging. Thanks!

I'm waiting a bit to submit a new version to CRAN to avoid getting an earful from the maintainers.

**Pull request merged**
